package com.bibledesktop.shared.api
import kotlin.test.*
class SourceAnnotationsTest {
 @Test fun validatesUtf16OffsetsAgainstActualPlainText(){val annotation=SourceAnnotations("available",addedWords=listOf(AnnotationRange(4,7)),source=AnnotationSource("mybible"),features=listOf("headings","footnotes","added_words","paragraphs").associateWith{"absent"});assertTrue(annotation.validFor("God was light."));assertFalse(annotation.copy(addedWords=listOf(AnnotationRange(4,99))).validFor("God was light."))}
 @Test fun legacyVerseHasNoInventedAnnotations(){val verse=BibleVerse(1,1,"Gen.1.1","<i>was</i>","was");assertNull(verse.annotations);assertNull(verse.markupFormat)}
 @Test fun rejectsSurrogateSplitOffsetsAndInvalidProvenance(){val source=SourceAnnotations("available",addedWords=listOf(AnnotationRange(1,2)),source=AnnotationSource("mybible"),features=listOf("headings","footnotes","added_words","paragraphs").associateWith{"absent"});assertFalse(source.validFor("😀"));assertFalse(source.copy(addedWords=emptyList(),source=AnnotationSource("mybible","bad")).validFor("😀"))}
 @Test fun inlineStrongRequiresPublishedExplicitPrefix(){val source=SourceAnnotations("available",strongTokens=listOf(SourceStrongAnnotation("430",1,3),SourceStrongAnnotation("H0430",2,3)),source=AnnotationSource("mybible"),features=listOf("headings","footnotes","added_words","paragraphs").associateWith{"absent"});val verse=BibleVerse(1,1,"Gen.1.1","raw","God",annotations=source);assertEquals(listOf("H430"),verse.explicitSourceStrongTokens().map{it.number})}
 @Test fun headingsAcceptActualStoriesAndBibleQuoteSourceKinds(){listOf("mybible_stories","biblequote_heading").forEach{kind->val source=SourceAnnotations("available",source=AnnotationSource("mybible"),headings=listOf(HeadingAnnotation("h","Source heading",0,AnnotationSource(kind,"a".repeat(64)))),features=listOf("headings","footnotes","added_words","paragraphs").associateWith{"absent"});assertTrue(source.validFor("God"))}}
 @Test fun companionFootnoteBodyKeepsActualFileProvenance(){val source=SourceAnnotations("available",source=AnnotationSource("mybible"),footnotes=listOf(FootnoteAnnotation("f","[1]","Companion body",3,"footnote",true,AnnotationSource("mybible_footnotes","a".repeat(64)))),features=listOf("headings","footnotes","added_words","paragraphs").associateWith{"absent"});assertTrue(source.validFor("God"))}
}
