<script setup lang="ts">
import {computed,ref} from 'vue'
import MobileShell from '@/components/MobileShell.vue'
import {useI18n} from '@/i18n'
import {readerHelpMessages} from '@/i18n/readerHelp'
const {language}=useI18n(),text=computed(()=>readerHelpMessages[language.value]),motion=ref<'horizontal'|'vertical'>('horizontal')
</script>
<template><MobileShell back-to="/more"><section class="reader-help"><h1>{{text.title}}</h1><details v-for="section in text.sections" :key="section[0]" open><summary>{{section[0]}}</summary><p>{{section[1]}}</p></details><section class="gesture-demo"><h2>{{text.demo}}</h2><div class="buttons"><button :aria-pressed="motion==='horizontal'" @click="motion='horizontal'">{{text.horizontal}}</button><button :aria-pressed="motion==='vertical'" @click="motion='vertical'">{{text.vertical}}</button></div><div :class="['demo-viewport',motion]" role="img" :aria-label="motion==='horizontal'?text.horizontal:text.vertical"><p>{{text.sample}}</p><i class="marker" aria-hidden="true"/><span class="finger" aria-hidden="true">●</span></div></section></section></MobileShell></template>
<style scoped>.reader-help{padding:16px;display:grid;gap:16px}.reader-help details{padding:14px;background:var(--white);border-radius:12px}.reader-help summary{font-weight:700;cursor:pointer}.reader-help p{line-height:1.65;white-space:pre-line}.buttons{display:flex;gap:8px;flex-wrap:wrap}.demo-viewport{position:relative;height:170px;overflow:hidden;border:1px solid var(--muted);border-radius:12px;margin-top:12px;padding:12px;background:var(--white)}.demo-viewport p{position:relative;z-index:1;font-size:16px;line-height:40px;margin:0}.finger{position:absolute;z-index:3;left:15px;top:35px;color:var(--brand-blue,#1e5aa8);font-size:26px}.marker{position:absolute;left:14px;top:24px;height:26px;background:#ffe49a;width:0}.horizontal .finger{animation:demo-horizontal 3s infinite}.horizontal .marker{animation:demo-marker 3s infinite}.vertical .finger{animation:demo-vertical 3s infinite}.vertical p{animation:demo-scroll 3s infinite}.vertical .marker{display:none}@keyframes demo-horizontal{0%,15%{transform:translateX(0)}70%,100%{transform:translateX(190px)}}@keyframes demo-marker{0%,15%{width:0}70%,100%{width:190px}}@keyframes demo-vertical{0%,15%{transform:translateY(0)}70%,100%{transform:translateY(-40px)}}@keyframes demo-scroll{0%,15%{transform:translateY(0)}70%,100%{transform:translateY(-40px)}}@media(prefers-reduced-motion:reduce){.horizontal .marker{width:190px}.horizontal .finger{transform:translateX(190px)}.demo-viewport *{animation:none!important}}</style>
