import type { MessageShape } from './index'
import type { ru } from './ru'

export const en: MessageShape<typeof ru> = {
  brand: 'Bible Desktop', brandSubtitle: 'My app', online: 'Online', offline: 'Offline', translationName: 'King James Version',
  navigation: { label: 'Main navigation', back: 'Back', today: 'Today', reading: 'Read', settings: 'Set up', education: 'Learning', more: 'More', prayers: 'Prayers', calendar: 'Calendar' },
  appearance: { settingsTitle: 'Settings', title: 'Appearance', classic: 'Classic', classicDescription: 'Blue day panel, light cards and classic headings', modern: 'Light', modernDescription: 'Clean blue style and the icon of the day', warm: 'Warm', warmDescription: 'Cream colours with green and terracotta accents' },
  readerActions: {
    myBookmarks: 'My bookmarks', myNotes: 'My notes', actions: 'Verse actions', search: 'Search the Bible', addNote: 'Add a note', copyLink: 'Copy link',
    saveNote: 'Save note', noteSaved: 'Note saved on this device.', noteFailed: 'Unable to save or open the note.', noteLocal: 'This note is stored only on this device.', searchHint: 'Words or a Bible reference', find: 'Find',
    noResults: 'No results found.', searchFailed: 'Search unavailable. Check your connection to the API.', bookmark: 'Bookmark', note: 'Note', audio: 'Audio', share: 'Share', size: 'Size', theme: 'Theme',
    selectVerse: 'Tap the text to select a verse.', shared: 'Link copied.', shareFailed: 'Unable to share. Please try again.', noteUnavailable: 'Notes are not connected yet.', audioUnavailable: 'Audio is not connected yet.',
  },
  welcome: { eyebrow: 'Personal app', title: 'Bible Desktop', intro: 'An Orthodox app for your spiritual life', startLabel: 'How to set up', quickTitle: 'Quick setup', quickDescription: 'All sections in one tap', manualTitle: 'Set up yourself', manualDescription: 'Choose sections and settings', restore: 'I already have an app', restoreDescription: 'Restore my data', verse: '“But seek ye first the kingdom of God…”', verseReference: 'Matt. 6:33', reassurance: 'You can change everything later', privacy: 'Privacy' },
  restore: { eyebrow: 'Restore', title: 'Restore my app', description: 'Restoring via a personal link or a short code will be available here.', notice: 'Server profile not connected yet. Local settings are saved automatically on this device.' },
  setup: {
    quickEyebrow: 'Quick setup', manualEyebrow: 'Manual setup', title: 'Build your app', editTitle: 'Set up your app', intro: 'Choose what matters now — you can change it later.',
    interfaceLanguageTitle: 'App language', interfaceLanguageIntro: 'Changes menus and labels. Reading languages are chosen separately.', russian: 'Русский', german: 'Deutsch', churchSlavonic: 'Church Slavonic', churchSlavonicCivil: 'Church Slavonic · civil script',
    presetTitle: 'Where shall we start?', presetIntro: 'Choose an option that suits you. It is just a starting point.', sectionsTitle: 'What would you like to add?', sectionsIntro: 'Keep only the sections you will use.',
    translationTitle: 'Bible translations', translationDescription: 'You can select several translations in different languages.', translationsLoading: 'Loading available translations…', translationsUnavailable: 'The translation catalogue is currently unavailable.', quickTranslationTitle: 'Main Bible translation', addTranslations: 'Add translations in other languages',
    prayerLanguagesTitle: 'Prayer text languages', prayersTitle: 'Prayer and worship', morningPrayer: 'Morning prayers', eveningPrayer: 'Evening prayers', prayerBook: 'Prayer book', akathists: 'Akathists', canons: 'Canons', horologion: 'Horologion',
    calendarTitle: 'Church calendar', calendarMajor: 'Main feasts and events', calendarAll: 'All available events', homeDisplay: 'On the home screen', calendarHome: { oldStyle: 'Old-style date', fasting: 'Fasting and meals', commemorations: 'Feasts and commemorations', readings: 'Daily readings', compact: 'Brief summary' },
    notificationsTitle: 'Reminders', notificationsToggle: 'Remind me every day', notificationsHint: 'System permission will be requested after setup', notificationTime: 'Reminder time', sectionRequired: 'Choose at least one section.', continue: 'Review choices', summaryTitle: 'Your app is ready', summaryIntro: 'Review your choices — you can change them at any time.',
    summaryPreset: 'Preset', summaryLanguage: 'App language', summaryTranslations: 'Bible translations', summaryPrayerContent: 'Prayer section', summarySections: 'Sections', summaryNotifications: 'Reminder', disabled: 'Off', create: 'Create my app', save: 'Save changes', change: 'Change choices', changePreset: 'Choose a different preset',
  },
  presets: { daily: { title: 'Every day', description: 'Bible, prayer and calendar', icon: '/app-icons/calendar.png' }, bible: { title: 'Bible reading', description: 'Text and study', icon: '/app-icons/library.png' }, prayer: { title: 'Prayer', description: 'Prayer rules and prayer book', icon: '/app-icons/prayers.png' }, calendar: { title: 'Church calendar', description: 'Feasts and daily readings', icon: '/app-icons/calendar.png' }, education: { title: 'Learning', description: 'Alphabet and learning apps', icon: '/app-icons/library.png' } },
  sections: { bible: { title: 'Bible', description: 'Translations and reading', icon: '/app-icons/library.png' }, prayers: { title: 'Daily prayer', description: 'Prayer rules and prayer book', icon: '/app-icons/prayers.png' }, calendar: { title: 'Church calendar', description: 'Feasts and readings', icon: '/app-icons/calendar.png' }, study: { title: 'Learning', description: 'Alphabet and learning apps', icon: '/app-icons/library.png' } },
  today: {
    clock: 'Clock', eyebrow: 'My day', title: 'Today', intro: 'Your chosen sections in one peaceful space.', profileLabel: 'Local profile', yourApp: 'Your app', customize: 'Set up', bibleAction: 'Open saved reading', configured: 'Added to profile', nextStage: 'Coming soon', localTitle: 'Settings saved on this device', localDescription: 'Available without an account or internet', prayersDescription: 'Prayer book, akathists and selected rules', calendarDescription: 'Commemorations, fasting and daily readings', notificationsTitle: 'Reminders', notificationsDescription: 'Categories, time and permissions', profileTitle: 'Profile and transfer', profileDescription: 'Link, sync, export and deletion', diagnosticsTitle: 'Diagnostics', diagnosticsDescription: 'Local anonymous summary for support', educationDescription: 'Slavonic alphabet, numerals and other learning apps', calendarDay: 'Church day', details: 'Details', allCommemorations: 'All commemorations', continue: 'Continue', storageTitle: 'Offline storage', storageDescription: 'Saved texts and bookmarks', setupDescription: 'Sections, apps and home screen',
  },
  education: { eyebrow: 'Learning', title: 'Learning apps', empty: 'Choose a learning app in settings.', selectRequired: 'Choose at least one learning app.', showClock: 'Clock with seconds on the home screen', showProgress: 'Learning progress on the home screen', clockTitle: 'Church Slavonic clock', progress: '{count} of {total} letters learned', goal: 'Today: {count} of {total} exercises', loadFailed: 'Unable to open the learning profile.', retry: 'Retry', intro: 'Apps and tools in the Biblia App ecosystem.', open: 'Open app', types: { standalone: 'Standalone app', plugin: 'Plugin', bot: 'Bot' }, apps: { azbuka: { title: 'Slavonic alphabet and numerals', description: 'Letters, exercises and Church Slavonic numbers from 1 to 999.' } } },
  prayers: { eyebrow: 'Prayer and worship', title: 'My prayer texts', loading: 'Loading selected texts…', offline: 'Offline — showing saved prayers.', unavailable: 'Unable to open prayer texts.', empty: 'Texts for the selected languages and sections are not published yet.', morning: 'Morning prayers', evening: 'Evening prayers', prayerBook: 'Prayer book', akathists: 'Akathists', canons: 'Canons', horologion: 'Horologion', loadingPrayer: 'Loading text…', notFound: 'Text not found.', savedOffline: 'Text saved for offline reading.', openedOffline: 'Offline — showing a saved copy.', openFailed: 'Unable to open the text.', source: 'Source' },
  calendar: {
    serviceTexts: 'Liturgical texts of the day', serviceFailed: 'Unable to load liturgical texts.', troparion: 'Troparion', kontakion: 'Kontakion', referenceText: 'Reference text — not an assigned service order', sunday: 'Sunday', redDays: 'Sundays and great feasts', typikonSigns: 'Typikon signs', dayRules: 'Instructions for the day', tone: 'Tone', weekAfterPentecost: 'Week after Pentecost', day: 'Day', week: 'Week', month: 'Month', view: 'Calendar view', openIcon: 'Open icon', close: 'Close', eyebrow: 'Church calendar', loading: 'Loading calendar…', offline: 'Offline — showing a saved day.', saved: 'Day saved for offline use.', failed: 'Unable to open the calendar.', previous: 'Previous day', next: 'Next day', oldStyle: 'Old style', fasting: 'Fasting', commemorations: 'Commemorations', readings: 'Daily readings', open: 'Open',
    horizon: 'Offline period', horizonHint: 'Save this day and the next 29 days', download: 'Download', stop: 'Stop', savingHorizon: 'Saving 30 calendar days…', horizonSaved: '30 calendar days are available offline.', horizonStopped: 'Calendar download stopped.', horizonFailed: 'Unable to save the calendar.', horizonProgress: 'Days saved: {count} of {total}', horizonImages: 'Calendar saved, but some icon previews could not be downloaded. Retry when online.', horizonRange: 'Available offline: {from} — {to}',
  },
  reader: { eyebrow: 'Bible', title: 'Reading', offline: 'Offline', chooseChapter: 'Choose chapter', openChapter: 'Open chapter', catalogLoading: 'Loading catalogue…', locationRestored: 'Reading position restored.', chooseBook: 'Choose a book and chapter.', booksUpdated: 'Book catalogue updated.', invalidChapter: 'Choose an existing chapter.', chapterSaved: 'Chapter opened and saved offline.', openedOffline: 'Offline — showing a saved chapter.', offlineTranslation: 'Offline translation', updateAvailable: 'update available', download: 'Download', update: 'Update', stop: 'Stop', notDownloaded: 'Not downloaded', chapters: 'chapters', downloadConfirm: 'Download the complete translation “{name}”? This may take a few minutes.', downloadStarting: 'Starting translation download…', downloadReady: 'The complete translation is available offline.', downloadStopped: 'Download stopped. The existing package was not changed.', previous: 'Previous chapter', next: 'Next chapter', chapterLabel: 'chapter', bookmark: 'Bookmark verse {verse}', bookmarkAdded: 'Verse {verse} bookmarked.', bookmarkRemoved: 'Bookmark for verse {verse} removed.' },
  storage: { notes: 'Notes', noNotes: 'No notes yet.', editNote: 'Edit', cancelEdit: 'Cancel', personalLocal: 'Saved in this browser on this domain. Data is not automatically transferred between domains.', loadFailed: 'Unable to open saved items. Please try again.', retry: 'Retry', eyebrow: 'Offline', title: 'Storage', intro: 'Manage downloaded texts separately from bookmarks and your profile.', savedChapters: 'chapters saved', approximateSize: 'approximate size', bookmarks: 'Bookmarks', content: 'Content', packages: 'Offline packages', deleteAll: 'Delete all', ready: 'Ready', noPackages: 'No complete translations downloaded yet.', chapters: 'Chapters', saved: 'Saved', delete: 'Delete', deleteChapter: 'Delete chapter', noChapters: 'No chapters saved yet.', personal: 'Personal', noBookmarks: 'No bookmarks yet.', chapterRemoved: 'Local chapter deleted. Bookmarks and settings kept.', contentRemoved: 'Offline texts deleted. Bookmarks and profile kept.', bookmarkRemoved: 'Bookmark removed.', removeChapterConfirm: 'Delete the local copy of “{name}, chapter {chapter}”?', clearConfirm: 'Delete all downloaded Bible texts? Bookmarks and profile will be kept.' },
  notifications: { eyebrow: 'Reminders', title: 'Your rhythm', intro: 'Enable only the categories you need. System permission will be requested after saving.', morning: 'Morning prayer', morningHint: 'A peaceful start to the day', evening: 'Evening prayer', eveningHint: 'Prayers before sleep', reading: 'Bible reading', readingHint: 'Continue from the last position', calendar: 'Church calendar', calendarHint: 'Commemorations and daily readings', time: 'Time', saving: 'Saving…', save: 'Save schedule', scheduleUpdated: 'Schedule updated for the next 14 days.', saved: 'Settings saved. System notifications work on Android and iOS.', denied: 'Settings saved, but system permission was not granted.', failed: 'Unable to update reminders.', platform: 'Platform', permission: 'System permission', nativeOnly: 'Android/iOS only', pending: 'Scheduled', push: 'Push updates', pushStatus: 'server ready; APNs/FCM registration needed' },
  restoreFlow: { eyebrow: 'Restore', title: 'Restore my app', intro: 'Use your personal link or short code. This replaces the local configuration on this device.', linkTitle: 'Personal link', pasteLink: 'Paste link', openProfile: 'Open profile', or: 'or', codeTitle: 'Recovery code', codeLabel: 'Four-group code', recover: 'Restore and replace code', invalidLink: 'Invalid personal link.', restoredLink: 'Profile restored using the personal link.', restoredCode: 'Profile restored. New code: {code}', failed: 'Unable to restore the profile.' },
  profile: { eyebrow: 'Transfer and recovery', title: 'My profile', intro: 'No account is required. The secret is kept only until this session ends.', createTitle: 'Create a personal link', createIntro: 'The server saves your configuration, not reading texts or bookmarks.', create: 'Create a protected profile', syncTitle: 'Synchronisation', profileId: 'Profile ID', revision: 'Revision', queue: 'Queue', sync: 'Sync now', linkTitle: 'Personal link', linkIntro: 'The secret follows # and is not sent to the web server when the link is opened.', copyLink: 'Copy link', recoveryTitle: 'New recovery code', recoveryIntro: 'The code is shown only now and is replaced after recovery.', copyCode: 'Copy code', secretNeeded: 'For server actions, open your personal link or restore using a code.', export: 'Export JSON', deleteRemote: 'Delete from server', accountTitle: 'Account — optional', accountIntro: 'Account linking will be added after a shared Bible Desktop sign-in scheme is chosen. Profiles and recovery work without it.', privacy: 'Privacy policy', deleteLocal: 'Delete local profile', created: 'Profile created. Save your link and new recovery code.', synced: 'Local changes synchronised.', credentialsNeeded: 'Open your personal link or use the recovery code.', noChanges: 'No changes to send.', copied: '{label} copied.', exportReady: 'Export prepared without recovery secrets.', deleteRemoteConfirm: 'Delete the server profile? Local settings will stay on this device.', remoteDeleted: 'Server profile deleted. Local settings kept.', deleteLocalConfirm: 'Delete the local profile from this device? Downloaded texts and bookmarks will be kept.', failed: 'Action failed.' },
  diagnostics: { eyebrow: 'Pilot support', title: 'Diagnostics', intro: 'This summary stays on this device and contains no texts, queries, links or tokens.', journey: 'Main journey', completion: 'Setup completion', errors: 'Errors by category', copy: 'Copy summary', clear: 'Clear', dataUse: 'How data is used', noData: 'no data', copied: 'Anonymous summary copied.', clearConfirm: 'Clear the local diagnostics summary?', cleared: 'Local summary cleared.', labels: { app_opened: 'App opens', constructor_opened: 'Setup opens', constructor_completed: 'Completed setups', profile_created: 'Server profiles created', offline_download_completed: 'Successful offline downloads', notification_schedule_saved: 'Schedules saved', unexpected: 'Unexpected errors', offline_download: 'Offline download errors', profile_restore: 'Recovery errors', profile_sync: 'Sync errors', notification_schedule: 'Scheduling errors' } },
  privacy: { eyebrow: 'Privacy', title: 'Privacy policy', updated: 'Last updated: 18 September 2026.', dataTitle: 'Data used by the app', dataText: 'Selected sections, notification settings, downloaded texts, reading position, bookmarks, verse notes and aggregate diagnostic counters are stored on your device. Reading, prayer, note and search contents are not recorded in analytics.', profileTitle: 'Personal profile', profileText: 'If you choose to create a personal link, Bible Desktop stores your app configuration, a random profile ID, revision and technical timestamps. The link secret is stored only as a hash. The recovery code is replaced after use.', localText: 'Downloaded Bible texts, bookmarks, verse notes and local diagnostics are not sent to the server profile.', notificationTitle: 'Notifications and technical data', notificationText: 'Local notifications are created on your device with your permission. If remote push notifications are enabled, the device token is encrypted on the server and can be revoked. The server may process IP addresses and standard technical logs for security and troubleshooting.', controlTitle: 'Managing your data', controlText: 'Under “Profile and transfer”, you can export the server configuration and separately delete the server and local profiles. Downloaded content and bookmarks are managed under “Offline storage”.', thirdTitle: 'Third parties', thirdText: 'The app does not sell data or contain advertising SDKs. Apple and Google process the platform data required for installation and system notifications under their own policies.', contactTitle: 'Contact', contactBefore: 'Bible Desktop operates this service. For questions about data and deletion, use the', contactLink: 'Bible Desktop contact page' },
  eyebrow: 'My Bible', title: 'God’s word every day', intro: 'Save a chapter to read even without internet.', cardEyebrow: 'Reading', cardTitle: 'Choose a chapter', translation: 'Translation', book: 'Book', chapter: 'Chapter', download: 'Download chapter', openOffline: 'Saved', notification: 'Remind me', notificationTitle: 'Bible Desktop', notificationBody: 'The test reminder works.', reading: 'Read', loading: 'Loading…', saved: 'Chapter downloaded and saved locally.', offlineOpened: 'Local copy opened.', offlineMissing: 'This chapter is not saved yet.', notificationScheduled: 'The reminder will appear in about 10 seconds.', notificationUnsupported: 'Local reminders are tested in Android or iOS builds.', notificationDenied: 'Notification permission was not granted.', unknownError: 'Unknown error.',
}
