export const verseSearchMessages = {
  ru: { exact: 'Точные слова', phrase: 'Фраза', partial: 'Фрагменты слов', strong: 'Номер Стронга', all: 'Вся Библия', old: 'Ветхий Завет', new: 'Новый Завет', psalms: 'Псалтирь', modes: 'Режим поиска', scope: 'Область', translations: 'Переводы', more: 'Показать ещё', found: 'Показано совпадений', local: 'Без сети: только сохранённые главы. Области Ветхого/Нового Завета без сети недоступны.', invalid: 'Введите минимум два символа; для Стронга — H430 или G25.', guide: 'Точные слова сохраняют форму и диакритику. Фраза ищет соседние слова, фрагменты — части слов. Показанное число не является полным количеством совпадений.', exhausted: 'Все страницы просмотрены', progress: 'Есть ещё страницы. Нажмите «Показать ещё», даже если здесь нет точных совпадений.' },
  de: { exact: 'Exakte Wörter', phrase: 'Phrase', partial: 'Wortteile', strong: 'Strong-Nummer', all: 'Ganze Bibel', old: 'Altes Testament', new: 'Neues Testament', psalms: 'Psalmen', modes: 'Suchmodus', scope: 'Bereich', translations: 'Übersetzungen', more: 'Mehr anzeigen', found: 'Angezeigte Treffer', local: 'Offline: Nur gespeicherte Kapitel. Altes/Neues Testament als Bereich ist offline nicht verfügbar.', invalid: 'Mindestens zwei Zeichen; für Strong: H430 oder G25.', guide: 'Exakte Wörter behalten Form und Akzente. Phrasen suchen aufeinanderfolgende Wörter, Wortteile suchen Teile. Die angezeigte Zahl ist keine Gesamtzahl.', exhausted: 'Alle Seiten gelesen', progress: 'Weitere Seiten vorhanden. „Mehr anzeigen“ auch bei einer Seite ohne exakte Treffer wählen.' },
  uk: { exact: 'Точні слова', phrase: 'Фраза', partial: 'Фрагменти слів', strong: 'Номер Стронга', all: 'Уся Біблія', old: 'Старий Завіт', new: 'Новий Завіт', psalms: 'Псалтир', modes: 'Режим пошуку', scope: 'Область', translations: 'Переклади', more: 'Показати ще', found: 'Показано збігів', local: 'Без мережі: лише збережені розділи. Області Старого/Нового Завіту без мережі недоступні.', invalid: 'Щонайменше два символи; для Стронга — H430 або G25.', guide: 'Точні слова зберігають форму та діакритику. Фраза шукає сусідні слова, фрагменти — частини слів. Показане число не є загальним.', exhausted: 'Усі сторінки переглянуто', progress: 'Є ще сторінки. Натисніть «Показати ще», навіть якщо тут немає точних збігів.' },
  en: { exact: 'Exact words', phrase: 'Phrase', partial: 'Word fragments', strong: 'Strong number', all: 'Whole Bible', old: 'Old Testament', new: 'New Testament', psalms: 'Psalms', modes: 'Search mode', scope: 'Scope', translations: 'Translations', more: 'Show more', found: 'Matches shown', local: 'Offline: Saved chapters only. Old/New Testament scopes are unavailable offline.', invalid: 'Enter at least two characters; for Strong: H430 or G25.', guide: 'Exact words retain form and accents. Phrases find consecutive words; fragments find word parts. The displayed count is not a total.', exhausted: 'All pages viewed', progress: 'More pages available. Choose “Show more” even if this page has no exact matches.' },
} as const
export const morphologyMessages = {
  ru: { morphology:'По словоформам', morphologyHint:'Учитываются словоформы поддерживаемых языков; если совпадений нет, возможны близкие результаты. Без сети RU/DE/EN ищутся только в сохранённых главах.' },
  de: { morphology:'Wortformen', morphologyHint:'Wortformen unterstützter Sprachen; ohne Treffer können ähnliche Ergebnisse erscheinen. Offline werden RU/DE/EN nur in gespeicherten Kapiteln gesucht.' },
  uk: { morphology:'За словоформами', morphologyHint:'Словоформи підтримуваних мов; за відсутності збігів можливі близькі результати. Без мережі RU/DE/EN шукаються лише в збережених розділах.' },
  en: { morphology:'Word forms', morphologyHint:'Word forms for supported languages; when there are no matches, similar results may appear. Offline, RU/DE/EN search saved chapters only.' },
} as const
