import {describe,it,expect} from 'vitest'
import {geographicPlaces,projectGeo,geoRoutePoints,geoViewport,transformGeoViewport,type GeoData} from './geography'
const data:GeoData={schema:1,referenceSystem:'source',sources:[],land:[],places:[{id:'a',name:'Jerusalem',aliases:['Jebus'],verses:['Acts.1.4'],locations:[{id:'x',name:'Old City',lon:35.23,lat:31.78,score:500,type:'source'}]},{id:'b',name:'Other',verses:['Acts.1.5'],locations:[]}]}
describe('published geography',()=>{
 it('projects real coordinates without guessing or accepting invalid latitude',()=>{expect(projectGeo(0,0)).toEqual([500,250]);expect(projectGeo(180,-90)).toEqual([1000,500]);expect(()=>projectGeo(181,0)).toThrow();expect(()=>projectGeo(0,NaN)).toThrow()})
 it('searches published variants and exact canonical references, not chapter approximations',()=>{expect(geographicPlaces(data,'jebus',['Acts.1.4']).map(p=>p.id)).toEqual(['a']);expect(geographicPlaces(data,'old city',['Acts.1.5'])).toEqual([]);expect(geographicPlaces(data,'',['Acts.1.40'])).toEqual([])})
 it('never invents route coordinates for unlocated or unattested stops',()=>{expect(geoRoutePoints(data,{id:'r',kind:'schematic',source:'Acts',stops:[{place_id:'a',osis:'Acts.1.5'},{place_id:'b',osis:'Acts.1.5'}]})).toEqual([]);expect(geoRoutePoints(data,{id:'r',kind:'schematic',source:'Acts',stops:[{place_id:'a',osis:'Acts.1.4'}]})).toEqual([projectGeo(35.23,31.78)])})
 it('centers actual located results and preserves signed source scores',()=>{const located={...data.places[0]!,locations:[{...data.places[0]!.locations[0]!,score:-422}]};expect(geoViewport([located]).center).toEqual(projectGeo(35.23,31.78));expect(geoViewport([located]).scale).toBe(32);expect(geographicPlaces({...data,places:[located]},'')[0]?.locations[0]?.score).toBe(-422);expect(geoViewport([])).toEqual({center:[500,250],scale:1})})
 it('anchors a pinch at its real midpoint and allows simultaneous two-finger pan',()=>{const bounds={left:0,top:0,width:1000,height:500};expect(transformGeoViewport([500,250],1,bounds,[{x:400,y:250},{x:600,y:250}],[{x:300,y:250},{x:700,y:250}])).toEqual({center:[500,250],scale:2});expect(transformGeoViewport([500,250],1,bounds,[{x:400,y:250},{x:600,y:250}],[{x:400,y:250},{x:800,y:250}])).toEqual({center:[450,250],scale:2});expect(transformGeoViewport([500,250],1,bounds,[{x:500,y:250}],[{x:600,y:250}])).toEqual({center:[400,250],scale:1})})
})
