import { isCommentaryAnnotations } from '@/api/commentaryAnnotations'
import type { BookContents,BookPage,StudyArticle,StudyBook,CommentaryPage,CommentaryEntry,CommentaryModule } from '@/api/study'
import { installedStudyPackages,type InstalledStudyPackage } from './studyPackages'
import { studyPackageRows } from './studyPackageLookup'
const id=(value:unknown)=>{if(typeof value!=='number'||!Number.isSafeInteger(value)||value<=0)throw new Error('Package API alias unavailable');return value}
const nullable=(value:unknown)=>typeof value==='string'?value:null
function studyBook(pack:InstalledStudyPackage,row:Record<string,unknown>):StudyBook{return{id:id(row.api_id),slug:String(row.id),title:String(row.title),author:nullable(row.author),description:nullable(row.description),module_code:pack.manifest.id}}
function section(row:Record<string,unknown>):StudyArticle{return{id:id(row.api_id),title:nullable(row.title),author:nullable(row.author),chapter_from:Number(row.chapter_from),verse_from:Number(row.verse_from),chapter_to:typeof row.chapter_to==='number'?row.chapter_to:null,verse_to:typeof row.verse_to==='number'?row.verse_to:null,book_osis_code:nullable(row.book_osis),body:String(row.body),annotations:isCommentaryAnnotations(row.annotations)?row.annotations:null}}
async function packs(){return(await installedStudyPackages()).filter(p=>p.manifest.kind==='commentary')}
async function findBook(book:number){for(const pack of await packs()){const rows=await studyPackageRows(pack,'books.jsonl',{limit:Number.MAX_SAFE_INTEGER});const row=rows.rows.find(r=>r.api_id===book);if(row)return{pack,row}}return undefined}
export async function installedStudyBooks(q:string,offset:number):Promise<BookPage|undefined>{const sources=await packs();if(!sources.length)return undefined;const results:StudyBook[]=[];for(const pack of sources){const page=await studyPackageRows(pack,'books.jsonl',{limit:Number.MAX_SAFE_INTEGER});for(const row of page.rows){if(q.trim()&&!`${row.title??''} ${row.author??''}`.toLocaleLowerCase().includes(q.trim().toLocaleLowerCase()))continue;results.push(studyBook(pack,row))}}results.sort((a,b)=>a.title.localeCompare(b.title)||a.id-b.id);return{data:results.slice(offset,offset+20),total:results.length}}
export async function installedStudyContents(book:number,offset:number):Promise<BookContents|undefined>{const found=await findBook(book);if(!found)return undefined;const data=await studyPackageRows(found.pack,'entries.jsonl',{entry:String(found.row.id),limit:Number.MAX_SAFE_INTEGER});data.rows.sort((a,b)=>Number(a.order)-Number(b.order)||Number(a.api_id)-Number(b.api_id));return{book:studyBook(found.pack,found.row),sections:data.rows.slice(offset,offset+20).map(section),total:data.total}}
export async function installedStudyArticle(book:number,article:number):Promise<StudyArticle|undefined>{const found=await findBook(book);if(!found)return undefined;const data=await studyPackageRows(found.pack,'entries.jsonl',{entry:String(found.row.id),limit:Number.MAX_SAFE_INTEGER});const row=data.rows.find(r=>r.api_id===article);if(!row)throw new Error('Installed section unavailable');return section(row)}
export async function installedCommentaryModules():Promise<CommentaryModule[]>{return(await packs()).map(pack=>({code:pack.manifest.id,name:String(pack.metadata.name??pack.manifest.id),short_name:null,entries_count:Number(pack.metadata.entries_count??0)}))}
export async function installedCommentaries(book:string,chapter:number|null,codes:string[],offset:number):Promise<CommentaryPage|undefined>{const sources=(await packs()).filter(p=>codes.includes(p.manifest.id));if(sources.length!==codes.length)return undefined;const entries:CommentaryEntry[]=[];for(const pack of sources){const page=await studyPackageRows(pack,'entries.jsonl',{book,limit:Number.MAX_SAFE_INTEGER});for(const row of page.rows){const first=Number(row.chapter_from),last=typeof row.chapter_to==='number'?row.chapter_to:first;if(chapter===null?first!==0:first!==0&&(first>chapter||last<chapter))continue;entries.push({...section(row),commentary_book_id:typeof row.commentary_book_api_id==='number'?row.commentary_book_api_id:null,module_code:pack.manifest.id,module_name:String(pack.metadata.name??pack.manifest.id)})}}entries.sort((a,b)=>a.id-b.id);return{book,chapter,entries:entries.slice(offset,offset+10),total:entries.length}}
