import {describe,it,expect}from'vitest'
import {guardedReferences,referenceGroups}from'./verseStudy'
import{referenceCopyText,referencePreviewText}from'./referenceDisplay'
import{isReferenceVersification,type StudyReferences,type ReferenceVersification}from'@/api/verseStudy'
const sample=(versification?:ReferenceVersification):StudyReferences=>({verse:{id:1,osis_ref:'Joel.3.1'},translation_code:'X',references:[{id:1,versification,target:{verse_id:2,osis_ref:'Joel.3.2',reference:'Joel 3:2',book_slug:'joel',chapter_number:3,verse_number:2,text:'Cached text from a possibly different numbering'}}]})
describe('cross-reference numbering guard',()=>{
 it('hides old cached or installed text when the package has no mapping status',()=>{const value=guardedReferences(sample());expect(value.references[0]?.versification?.status).toBe('unknown');expect(value.references[0]?.target.text).toBeNull();const group=referenceGroups(sample().references)[0]!;expect(referenceCopyText(group,'X')).not.toContain('Cached text')})
 it('hides raw and ambiguous previews while retaining stored reference and provenance',()=>{for(const status of ['raw','ambiguous']as const){const value=guardedReferences(sample({status,source_profile:'MT',edition_profile:'LXX',map_version:'v1'}));expect(value.references[0]?.target.text).toBeNull();expect(value.references[0]?.target.osis_ref).toBe('Joel.3.2');expect(value.references[0]?.versification?.source_profile).toBe('MT')}})
 it('requires full verified provenance to show text',()=>{expect(guardedReferences(sample({status:'verified',source_profile:'MT',edition_profile:'MT',map_version:null})).references[0]?.target.text).toBeNull();expect(guardedReferences(sample({status:'verified',source_profile:'MT',edition_profile:'MT',map_version:'v1'})).references[0]?.target.text).toContain('Cached text');expect(isReferenceVersification({status:'exact'})).toBe(false)})
 it('distinguishes hidden unverified previews from actual verified missing passages',()=>{expect(referencePreviewText(guardedReferences(sample()).references[0]!.target,'Missing verse')).toBe('');const verified=guardedReferences(sample({status:'verified',source_profile:'MT',edition_profile:'MT',map_version:'v1'})).references[0]!.target;expect(referencePreviewText({...verified,text:null},'Missing verse')).toBe('Missing verse');expect(referencePreviewText(verified,'Missing verse')).toContain('Cached text')})
})
