import type{BibleVerse}from'@/api/contracts'
import type{ReaderPreferences}from'@/profile/readerPreferences'
import{wordSegments,type WordMark}from'./personalStudy'
import{isSourceAnnotations}from'@/api/sourceAnnotations'
export function inlineSourceStrongTokens(verse:BibleVerse){return verse.annotations?.status==='available'&&isSourceAnnotations(verse.annotations,verse.plain_text)?verse.annotations.strong_tokens.filter(token=>/^[HG]\d{1,5}$/iu.test(token.strong_number)&&Number(token.strong_number.slice(1))>0).map(token=>({...token,strong_number:token.strong_number[0]!.toUpperCase()+Number(token.strong_number.slice(1))})):[]}
export function sourceVerseSegments(verse:BibleVerse,code:string,marks:WordMark[],preferences:ReaderPreferences){
 const annotation=verse.annotations?.status==='available'&&isSourceAnnotations(verse.annotations,verse.plain_text)?verse.annotations:undefined
 const words=wordSegments(verse.plain_text,code,verse.osis_ref,marks)
 const strong=inlineSourceStrongTokens(verse),emphasis=[...annotation?.emphasis??[],...annotation?.quotations??[]]
 const points=[...new Set([0,verse.plain_text.length,...words.flatMap(word=>[word.start,word.start+word.text.length]),...(annotation?.added_words.flatMap(range=>[range.start_utf16,range.end_utf16])??[]),...emphasis.flatMap(range=>[range.start_utf16,range.end_utf16]),...(annotation?.red_letters.flatMap(range=>[range.start_utf16,range.end_utf16])??[]),...strong.map(token=>token.offset_utf16),...(annotation?.headings.map(item=>item.offset_utf16)??[]),...(annotation?.footnotes.map(item=>item.offset_utf16)??[]),...(annotation?.paragraph_breaks.map(item=>item.offset_utf16)??[]),...(annotation?.line_breaks.map(item=>item.offset_utf16)??[])])].sort((a,b)=>a-b)
 return points.map((start,index)=>({start,text:preferences.clean||!preferences.paragraphs?verse.plain_text.slice(start,points[index+1]??start).replace(/\n/gu,' '):verse.plain_text.slice(start,points[index+1]??start),marks:words.find(word=>word.start<=start&&word.start+word.text.length>start)?.marks??[],added:!preferences.clean&&preferences.addedWords&&Boolean(annotation?.added_words.some(range=>start>=range.start_utf16&&start<range.end_utf16)),red:!preferences.clean&&Boolean(annotation?.red_letters.some(range=>start>=range.start_utf16&&start<range.end_utf16)),emphasis:!preferences.clean&&emphasis.some(range=>start>=range.start_utf16&&start<range.end_utf16),headings:!preferences.clean&&preferences.headings?annotation?.headings.filter(item=>item.offset_utf16===start)??[]:[],footnotes:!preferences.clean&&preferences.footnotes?annotation?.footnotes.filter(item=>item.offset_utf16===start)??[]:[],strongTokens:!preferences.clean&&preferences.strongNumbers?strong.filter(token=>token.offset_utf16===start):[],paragraph:!preferences.clean&&preferences.paragraphs&&Boolean(annotation?.paragraph_breaks.some(item=>item.offset_utf16===start)||start===0&&annotation?.paragraph_before),line:!preferences.clean&&preferences.paragraphs&&Boolean(annotation?.line_breaks.some(item=>item.offset_utf16===start))}))
}
