import{describe,it,expect}from'vitest'
import{sourceVerseSegments,inlineSourceStrongTokens}from'./sourceVerseDisplay'
import{defaultReaderPreferences}from'@/profile/readerPreferences'
import{isSourceAnnotations,type SourceAnnotations}from'@/api/sourceAnnotations'
import type{BibleVerse}from'@/api/contracts'
const annotations:SourceAnnotations={status:'available',paragraph_before:true,paragraph_breaks:[{offset_utf16:8}],line_breaks:[],headings:[{id:'h',text:'Source title',offset_utf16:0,source:{kind:'mybible',sha256:null}}],footnotes:[{id:'f',marker:'[1]',text:null,offset_utf16:3,kind:'footnote',body_available:false,source:{kind:'mybible',sha256:null}}],added_words:[{start_utf16:4,end_utf16:7}],emphasis:[],red_letters:[],strong_tokens:[],source:{kind:'mybible',sha256:null},features:{headings:'present',footnotes:'present',added_words:'present',paragraphs:'present'}}
const verse:BibleVerse={id:1,number:1,osis_ref:'Gen.1.1',text:'raw retained source',plain_text:'God was light.',has_strong_markup:false,markup_format:'mybible',annotations}
describe('actual source annotations display',()=>{
 it('keeps the underlying text and saved mark offsets while adding source events',()=>{const value=sourceVerseSegments(verse,'X',[],defaultReaderPreferences);expect(value.map(piece=>piece.text).join('')).toBe(verse.plain_text);expect(value.find(piece=>piece.added)?.text).toBe('was');expect(value[0]?.headings[0]?.text).toBe('Source title');expect(value.find(piece=>piece.start===3)?.footnotes[0]?.text).toBeNull();expect(value.some(piece=>piece.paragraph)).toBe(true)})
 it('clean mode hides annotations without changing source text or saved preferences',()=>{const value=sourceVerseSegments(verse,'X',[],{...defaultReaderPreferences,clean:true});expect(value.map(piece=>piece.text).join('')).toBe(verse.plain_text);expect(value.every(piece=>!piece.added&&!piece.paragraph&&!piece.line&&!piece.headings.length&&!piece.footnotes.length)).toBe(true)})
 it('never invents annotations from legacy HTML or invalid offsets',()=>{expect(sourceVerseSegments({...verse,annotations:undefined,text:'<i>was</i>'},'X',[],defaultReaderPreferences).some(piece=>piece.added)).toBe(false);expect(isSourceAnnotations({...annotations,added_words:[{start_utf16:0,end_utf16:999}]},verse.plain_text)).toBe(false);expect(sourceVerseSegments({...verse,annotations:{...annotations,status:'not_preserved'}},'X',[],defaultReaderPreferences).every(piece=>!piece.headings.length&&!piece.footnotes.length)).toBe(true)})
 it('rejects offsets inside surrogate pairs and malformed source provenance',()=>{expect(isSourceAnnotations({...annotations,headings:[],footnotes:[],paragraph_breaks:[],added_words:[{start_utf16:1,end_utf16:2}]},'😀')).toBe(false);expect(isSourceAnnotations({...annotations,source:{kind:'mybible',sha256:'bad'}},verse.plain_text)).toBe(false);expect(isSourceAnnotations({...annotations,features:{...annotations.features,headings:'guessed'}},verse.plain_text)).toBe(false)})
 it('uses real Strong offsets only for explicit prefixes and never guesses bare identifiers',()=>{const strongVerse={...verse,annotations:{...annotations,strong_tokens:[{strong_number:'430',token_order:1,offset_utf16:3,grammar_code:null,surface_text:null},{strong_number:'H0430',token_order:2,offset_utf16:7,grammar_code:null,surface_text:null}]}};expect(inlineSourceStrongTokens(strongVerse).map(token=>[token.strong_number,token.offset_utf16])).toEqual([['H430',7]]);expect(sourceVerseSegments(strongVerse,'X',[],{...defaultReaderPreferences,strongNumbers:true}).find(piece=>piece.start===7)?.strongTokens[0]?.strong_number).toBe('H430')})
 it('accepts published story and BibleQuote heading provenance without changing verse format',()=>{for(const kind of ['mybible_stories','biblequote_heading']){const value={...annotations,headings:[{id:'archive-heading',text:'Actual source heading',offset_utf16:0,source:{kind,sha256:'a'.repeat(64)}}]};expect(isSourceAnnotations(value,verse.plain_text)).toBe(true);expect(sourceVerseSegments({...verse,annotations:value},'X',[],defaultReaderPreferences)[0]?.headings[0]?.text).toBe('Actual source heading')}})
 it('accepts a real companion note body with its own file provenance',()=>{const value={...annotations,footnotes:[{...annotations.footnotes[0]!,text:'Actual companion body',body_available:true,source:{kind:'mybible_footnotes',sha256:'b'.repeat(64)}}]};expect(isSourceAnnotations(value,verse.plain_text)).toBe(true);expect(sourceVerseSegments({...verse,annotations:value},'X',[],defaultReaderPreferences).find(piece=>piece.start===3)?.footnotes[0]?.text).toBe('Actual companion body')})
})
