import { describe, expect, it } from 'vitest'
import { zipSync, strToU8 } from 'fflate'
import { decodeStudyPackage, packageRows } from './studyPackages'
import type { StudyPackage } from '@/api/studyPackages'
async function fixture(extra: Record<string,Uint8Array> = {}) { const zip=zipSync({'module.json':strToU8('{"schema":1,"kind":"dictionary","code":"MAPS"}\n'),'entries.jsonl':strToU8(`{"id":"${'a'.repeat(40)}","topic":"Jerusalem","body":"Text","order":1}\n`),'references.jsonl':strToU8(''),'links.jsonl':strToU8(''),'word_forms.jsonl':strToU8(''),'media_links.jsonl':strToU8(''),'media.jsonl':strToU8(''),...extra});const sha256=[...new Uint8Array(await crypto.subtle.digest('SHA-256',zip))].map(b=>b.toString(16).padStart(2,'0')).join('');const pack:StudyPackage={id:'MAPS',kind:'dictionary',version:sha256,sha256,bytes:zip.length,url:'/api/offline/packages/MAPS'};return{zip,pack} }
describe('complete study package integrity',()=>{
 it('validates the real ZIP/JSONL schema and article stable keys',async()=>{const{zip,pack}=await fixture();const decoded=await decodeStudyPackage(pack,zip);expect(decoded.metadata.code).toBe('MAPS');const rows=[];for await(const row of packageRows(decoded.files['entries.jsonl']!))rows.push(row);expect(rows).toHaveLength(1);expect(rows[0]!.topic).toBe('Jerusalem')})
 it('rejects altered archives and declared sizes before installing',async()=>{const{zip,pack}=await fixture();const altered=zip.slice();altered[10]^=1;await expect(decodeStudyPackage(pack,altered)).rejects.toThrow('checksum');await expect(decodeStudyPackage({...pack,bytes:pack.bytes+1},zip)).rejects.toThrow('size')})
 it('rejects foreign module identity, path traversal and oversized expansion',async()=>{const wrong=await fixture({'module.json':strToU8('{"schema":1,"kind":"dictionary","code":"OTHER"}')});await expect(decodeStudyPackage(wrong.pack,wrong.zip)).rejects.toThrow('identity');const traversal=await fixture({'../private.txt':strToU8('bad')});await expect(decodeStudyPackage(traversal.pack,traversal.zip)).rejects.toThrow('file');const normal=await fixture();await expect(decodeStudyPackage(normal.pack,normal.zip,1)).rejects.toThrow('space')})
 it('rejects corrupt article JSON without creating an installed marker',async()=>{const data=await fixture({'entries.jsonl':strToU8('{"id":"bad","topic":"Wrong","body":"Text"}\n')});await expect(decodeStudyPackage(data.pack,data.zip)).rejects.toThrow('article')})
})
