<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import type { BibleBook, BibleChapter } from '@/api/contracts'
import type { ChapterService } from '@/services/chapterService'
import { readWebChapter } from '@/services/webBibleLibrary'
import { useI18n } from '@/i18n'
import { readerControlMessages } from '@/i18n/readerControls'
const props = defineProps<{code:string; book:BibleBook; chapter:number; service:ChapterService}>()
const emit = defineEmits<{select:[chapter:number,verse:number]; close:[]}>()
const {language}=useI18n(), text=computed(()=>readerControlMessages[language.value])
const digital=ref(window.localStorage.getItem('bible-desktop:navigation-mode')==='digital'), selectedChapter=ref(props.chapter), position=ref(`${props.chapter}:1`), source=ref<BibleChapter>(), error=ref(false), busy=ref(false), retry=ref(0)
watch([()=>props.code,()=>props.book.slug,selectedChapter,retry],async([code,book,ch],_,cleanup)=>{let stale=false;cleanup(()=>stale=true);source.value=undefined;error.value=false;try{const value=await readWebChapter(props.service,String(code),String(book),Number(ch));if(!stale)source.value=value}catch{if(!stale)error.value=true}},{immediate:true})
function toggleMode(){digital.value=!digital.value;window.localStorage.setItem('bible-desktop:navigation-mode',digital.value?'digital':'visual')}
watch(position,value=>{if(digital.value){const ch=Number(value.trim().split(':')[0]);if(Number.isInteger(ch)&&ch>=1&&ch<=props.book.chapters_count)selectedChapter.value=ch}})
async function go(){const match=/^\s*(\d+)\s*(?::\s*(\d+)\s*)?$/u.exec(position.value),ch=Number(match?.[1]),verse=Number(match?.[2]||1);if(!match||ch<1||ch>props.book.chapters_count||verse<1){error.value=true;return}busy.value=true;error.value=false;try{const value=source.value?.chapter.number===ch?source.value:await readWebChapter(props.service,props.code,props.book.slug,ch);if(value.translation.code!==props.code||value.book.slug!==props.book.slug||value.chapter.number!==ch||!value.verses.some(v=>v.number===verse&&v.plain_text.trim()))throw Error('Unavailable verse');emit('select',ch,verse)}catch{error.value=true}finally{busy.value=false}}
</script>
<template><section class="verse-navigation" data-no-reader-gesture><header><h3>{{book.name}} {{selectedChapter}}</h3><button @click="emit('close')">{{text.close}}</button></header><button @click="toggleMode">{{digital?text.visual:text.digital}}</button><button @click="emit('select',1,0)">{{text.beginning}} · {{book.name}}</button><button @click="emit('select',selectedChapter,0)">{{text.beginning}} · {{selectedChapter}}</button><p>{{book.chapters_count}} · {{source?.verses.length ?? '…'}}</p><form v-if="digital" @submit.prevent="go"><label>{{text.digital}}<input v-model="position" inputmode="numeric" /></label><button :disabled="busy">{{text.go}}</button></form><template v-else><div class="navigation-grid"><button v-for="ch in book.chapters_count" :key="ch" :aria-pressed="selectedChapter===ch" @click="selectedChapter=ch">{{ch}}</button></div><hr/><div class="navigation-grid"><button v-for="verse in source?.verses.filter(v=>v.plain_text.trim())" :key="verse.number" @click="emit('select',selectedChapter,verse.number)">{{verse.number}}</button></div></template><p v-if="error" role="alert">{{text.invalid}} <button @click="retry++">↻</button></p></section></template>
<style scoped>.verse-navigation header{display:flex;justify-content:space-between;align-items:center}.navigation-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(3rem,1fr));gap:.5rem;max-height:35dvh;overflow:auto;padding:.5rem 0}.navigation-grid button{min-height:3rem}.verse-navigation>button{margin:.3rem}.verse-navigation input{max-width:8rem;margin:.5rem}.navigation-grid [aria-pressed=true]{font-weight:bold}</style>
