export interface AnnotationOffset {offset_utf16:number}
export interface AnnotationRange {start_utf16:number;end_utf16:number}
export interface AnnotationSource{kind:string;sha256:string|null}
export interface SourceHeadingAnnotation extends AnnotationOffset{id:string;text:string;source:AnnotationSource}
export interface SourceFootnoteAnnotation extends AnnotationOffset{id:string;marker:string|null;text:string|null;kind:'inline_note'|'footnote';body_available:boolean;source:AnnotationSource}
export interface SourceAnnotations {status:'available'|'not_preserved';paragraph_before:boolean|null;paragraph_breaks:AnnotationOffset[];line_breaks:AnnotationOffset[];headings:SourceHeadingAnnotation[];footnotes:SourceFootnoteAnnotation[];added_words:AnnotationRange[];emphasis:AnnotationRange[];red_letters:AnnotationRange[];quotations?:AnnotationRange[];strong_tokens:(AnnotationOffset&{strong_number:string;raw_number?:string|null;scope_source?:'marker'|'source_metadata'|'catalog_testament'|'unknown'|null;token_order:number;grammar_code:string|null;surface_text:string|null})[];source:AnnotationSource|null;features:Record<'headings'|'footnotes'|'added_words'|'paragraphs','present'|'absent'|'unknown'>}
const record=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null
export function isSourceAnnotations(value:unknown,text:string):value is SourceAnnotations{
 if(!record(value)||!['available','not_preserved'].includes(String(value.status))||!(value.paragraph_before===null||typeof value.paragraph_before==='boolean')||value.status==='available'&&value.source===null)return false
 const position=(n:unknown)=>Number.isInteger(n)&&Number(n)>=0&&Number(n)<=text.length&&!(Number(n)>0&&Number(n)<text.length&&text.charCodeAt(Number(n)-1)>=0xd800&&text.charCodeAt(Number(n)-1)<=0xdbff&&text.charCodeAt(Number(n))>=0xdc00&&text.charCodeAt(Number(n))<=0xdfff)
 const offset=(v:unknown)=>record(v)&&position(v.offset_utf16)
 const range=(v:unknown)=>record(v)&&position(v.start_utf16)&&position(v.end_utf16)&&Number(v.end_utf16)>Number(v.start_utf16)
 const source=(v:unknown)=>record(v)&&['mybible','biblequote','legacy_html','unknown','mybible_stories','biblequote_heading','mybible_footnotes'].includes(String(v.kind))&&(v.sha256===null||typeof v.sha256==='string'&&/^[a-f0-9]{64}$/iu.test(v.sha256))
 const array=(key:string,check:(v:unknown)=>boolean)=>Array.isArray(value[key])&&(value[key]as unknown[]).every(check)
 return array('paragraph_breaks',offset)&&array('line_breaks',offset)&&array('added_words',range)&&array('emphasis',range)&&array('red_letters',range)&&(value.quotations===undefined||array('quotations',range))&&array('headings',v=>offset(v)&&record(v)&&typeof v.id==='string'&&typeof v.text==='string'&&source(v.source))&&array('footnotes',v=>offset(v)&&record(v)&&typeof v.id==='string'&&(v.marker===null||typeof v.marker==='string')&&(v.text===null||typeof v.text==='string')&&typeof v.body_available==='boolean'&&['inline_note','footnote'].includes(String(v.kind))&&source(v.source))&&array('strong_tokens',v=>offset(v)&&record(v)&&typeof v.strong_number==='string'&&/^[HG]?[0-9]{1,5}$/iu.test(v.strong_number)&&Number(v.strong_number.replace(/^[HG]/iu,''))>0&&Number.isInteger(v.token_order)&&Number(v.token_order)>=0&&(v.raw_number===undefined||v.raw_number===null||typeof v.raw_number==='string')&&(v.scope_source===undefined||v.scope_source===null||['marker','source_metadata','catalog_testament','unknown'].includes(String(v.scope_source)))&&(v.grammar_code===null||typeof v.grammar_code==='string')&&(v.surface_text===null||typeof v.surface_text==='string'))&&(value.source===null||source(value.source))&&record(value.features)&&['headings','footnotes','added_words','paragraphs'].every(key=>['present','absent','unknown'].includes(String((value.features as Record<string,unknown>)[key])))
}
