<script setup lang="ts">
import {computed,nextTick,onMounted,onUnmounted,ref,watch} from 'vue'
import {useI18n} from '@/i18n'
import {geographyMessages} from '@/i18n/geography'
import {loadGeography,geographicPlaces,projectGeo,geoLandPath,geoRoutePoints,geoViewport,transformGeoViewport,type GeoData,type GeoPlace,type GeoLocation} from '@/services/geography'
const props=defineProps<{references?:string[];initialQuery?:string}>(),{language}=useI18n(),text=computed(()=>geographyMessages[language.value])
const data=ref<GeoData>(),error=ref(false),query=ref(props.initialQuery??''),context=ref(false),selected=ref<GeoPlace>(),variants=ref<Record<string,string>>({}),limit=ref(40),scale=ref(1),center=ref<[number,number]>([500,250]),frame=ref<HTMLElement>(),details=ref<HTMLElement>(),journey=ref(false)
const places=computed(()=>data.value?geographicPlaces(data.value,query.value,context.value?props.references:[]):[]),mapped=computed(()=>places.value.flatMap(place=>place.locations.map(location=>({place,location,point:projectGeo(location.lon,location.lat)})))),land=computed(()=>data.value?.land.map(geoLandPath)??[])
const viewBox=computed(()=>`${center.value[0]-500/scale.value} ${center.value[1]-250/scale.value} ${1000/scale.value} ${500/scale.value}`),route=computed(()=>data.value?.routes?.[0]),routePoints=computed(()=>data.value&&route.value?geoRoutePoints(data.value,route.value,variants.value).map(p=>p.join(',')).join(' '):'')
async function load(){error.value=false;try{data.value=await loadGeography()}catch{error.value=true}}
function choose(place:GeoPlace,location:GeoLocation|undefined=place.locations[0]){selected.value=place;if(location){variants.value={...variants.value,[place.id]:location.id};center.value=projectGeo(location.lon,location.lat);scale.value=Math.max(scale.value,8)}void nextTick(()=>details.value?.scrollIntoView({block:'nearest',behavior:'smooth'}))}
function reset(){center.value=[500,250];scale.value=1}
const fullscreen=ref(false),fallbackFullscreen=ref(false),pointers=new Map<number,{x:number;y:number}>()
let moved=false,fullscreenOpener:HTMLElement|undefined,oldOverflow=''
function down(event:PointerEvent){if((event.target as Element).closest('[data-geo-control]'))return;if(!pointers.size)moved=false;pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});if(!(event.target as Element).closest('[data-pin]'))frame.value?.setPointerCapture(event.pointerId)}
function move(event:PointerEvent){if(!pointers.has(event.pointerId))return;const old=[...pointers.values()];const previous=pointers.get(event.pointerId)!;pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});const points=[...pointers.values()],bounds=frame.value?.getBoundingClientRect();if(!bounds)return;const changed=transformGeoViewport(center.value,scale.value,bounds,old,points);center.value=changed.center;scale.value=changed.scale;if(Math.hypot(event.clientX-previous.x,event.clientY-previous.y)>1||points.length>1)moved=true}
function up(event:PointerEvent){pointers.delete(event.pointerId)}
async function openFullscreen(){fullscreenOpener=document.activeElement as HTMLElement;fullscreen.value=true;try{if(!frame.value?.requestFullscreen)throw Error();await frame.value.requestFullscreen()}catch{fallbackFullscreen.value=true;oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden'}void nextTick(()=>frame.value?.focus())}
async function closeFullscreen(){fullscreen.value=false;if(fallbackFullscreen.value)document.body.style.overflow=oldOverflow;fallbackFullscreen.value=false;if(document.fullscreenElement===frame.value)await document.exitFullscreen().catch(()=>undefined);fullscreenOpener?.focus({preventScroll:true})}
function fullscreenChanged(){if(!document.fullscreenElement&&!fallbackFullscreen.value)fullscreen.value=false}
function fullscreenKey(event:KeyboardEvent){if(event.key==='Escape'&&fullscreen.value){event.preventDefault();void closeFullscreen()}}
function zoom(amount:number){scale.value=Math.min(64,Math.max(1,scale.value*amount))}
watch([query,context,()=>props.references],()=>{limit.value=40;selected.value=undefined});watch(places,values=>{if(context.value||query.value.trim()){const viewport=geoViewport(values);center.value=viewport.center;scale.value=viewport.scale}});onMounted(()=>{void load();document.addEventListener('fullscreenchange',fullscreenChanged);window.addEventListener('keydown',fullscreenKey)});onUnmounted(()=>{document.removeEventListener('fullscreenchange',fullscreenChanged);window.removeEventListener('keydown',fullscreenKey);if(fallbackFullscreen.value)document.body.style.overflow=oldOverflow})
</script>
<style scoped>
.geo-atlas input[type=checkbox]{width:18px;height:18px;min-height:0;margin:0;flex:0 0 18px}
.geo-atlas input[type=range]{width:160px;min-height:24px;margin:0}
.geo-atlas nav label{flex-wrap:nowrap;font-size:14px}
</style>
<template><section class="geo-atlas"><h1>{{text.title}}</h1><p>{{text.uncertain}}</p><p>{{text.names}}</p><p v-if="!data&&!error" role="status">{{text.loading}}</p><p v-if="error" role="alert">{{text.error}} <button @click="load">{{text.retry}}</button></p><template v-if="data"><label>{{text.search}} <input v-model="query" type="search"></label><label v-if="references?.length"><input v-model="context" type="checkbox">{{text.context}} · {{references.join(', ')}}</label><nav><button @click="zoom(1.5)">＋</button><button @click="zoom(1/1.5)">−</button><label>{{text.zoom}} <input v-model.number="scale" type="range" min="1" max="64" step="0.5"></label><button @click="reset">{{text.reset}}</button><button @click="openFullscreen">{{text.fullscreen}}</button><label v-if="route"><input v-model="journey" type="checkbox">{{text.journey}}</label></nav><p v-if="journey">{{text.schematic}}</p>
<div class="geo-workspace"><div class="geo-visual"><div ref="frame" class="geo-frame" :class="{'geo-fallback-fullscreen':fallbackFullscreen}" tabindex="0" :aria-label="text.title" @pointerdown="down" @pointermove="move" @pointerup="up" @pointercancel="up" @wheel.prevent="zoom($event.deltaY<0?1.15:1/1.15)" @keydown.left.prevent="center=[center[0]-30/scale,center[1]]" @keydown.right.prevent="center=[center[0]+30/scale,center[1]]" @keydown.up.prevent="center=[center[0],center[1]-30/scale]" @keydown.down.prevent="center=[center[0],center[1]+30/scale]">
<nav v-if="fullscreen" class="geo-fullscreen-controls" data-geo-control @pointerdown.stop><button :aria-label="`${text.zoom} +`" @click="zoom(1.5)">＋</button><button :aria-label="`${text.zoom} −`" @click="zoom(1/1.5)">−</button><button @click="reset">{{text.reset}}</button><button @click="closeFullscreen">{{text.back}}</button></nav><svg :viewBox="viewBox" preserveAspectRatio="xMidYMid meet"><path v-for="(path,i) in land" :key="i" :d="path" fill="#dde1c6" stroke="#6a806c" :stroke-width="0.4/scale"/><polyline v-if="journey" :points="routePoints" fill="none" stroke="#9c3165" :stroke-width="2/scale" :stroke-dasharray="`${5/scale} ${3/scale}`"/><circle v-for="pin in mapped" :key="`${pin.place.id}:${pin.location.id}`" data-pin :cx="pin.point[0]" :cy="pin.point[1]" :r="(selected?.id===pin.place.id?5:3)/scale" :fill="selected?.id===pin.place.id?'#ac233f':'#18529d'" stroke="white" :stroke-width="0.7/scale" @click.stop="!moved && choose(pin.place,pin.location)"><title>{{pin.place.name}} · {{pin.location.name}} · {{pin.location.score??text.unknown}}</title></circle></svg></div>
<article v-if="selected" ref="details" class="geo-details"><h2>{{selected.name}}</h2><h3>{{text.variants}}</h3><button v-for="location in selected.locations" :key="location.id" :aria-pressed="variants[selected.id]===location.id" @click="choose(selected,location)">{{location.name||selected.name}} · {{location.lat}}, {{location.lon}} · {{location.type}} · {{location.score===null?text.unknown:`${text.score}: ${location.score}`}}</button><p v-if="!selected.locations.length">{{text.noCoordinates}}</p><details><summary>{{text.refs}} ({{selected.verses.length}})</summary><p>{{selected.verses.join(' · ')}}</p></details></article>
</div><aside class="geo-results"><p>{{places.length}}</p><p v-if="!places.length">{{text.empty}}</p><ul class="geo-list"><li v-for="place in places.slice(0,limit)" :key="place.id"><button @click="choose(place)">{{place.name}}</button> · {{place.locations.length}} <small>{{place.aliases?.join(' · ')}}</small></li></ul><button v-if="limit<places.length" @click="limit+=40">{{text.more}} ({{places.length-limit}})</button></aside></div><details><summary>{{text.sources}}</summary><p v-for="source in data.sources" :key="source.url"><a :href="source.url" target="_blank" rel="noopener noreferrer">{{source.name}}</a> · <a v-if="source.license_url" :href="source.license_url" target="_blank" rel="noopener noreferrer">{{source.license}}</a><span v-else>{{source.license}}</span></p></details></template></section></template>
<style scoped>.geo-atlas{padding:16px;display:grid;gap:12px}.geo-atlas p{margin:0;line-height:1.5}.geo-atlas nav{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.geo-atlas label{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.geo-frame{position:relative;height:52dvh;min-height:260px;overflow:hidden;touch-action:none;background:#c3dbe6;border:1px solid #6a806c;border-radius:8px}.geo-frame:fullscreen{height:100dvh}.geo-frame.geo-fallback-fullscreen{position:fixed;inset:0;width:100vw;height:100dvh;min-height:0;z-index:500;border-radius:0}.geo-fullscreen-controls{position:absolute;top:12px;left:12px;right:12px;z-index:2;background:var(--white,#fff);color:var(--ink,#17324a);padding:8px;border-radius:8px;box-shadow:0 2px 12px #0004}.geo-frame svg{width:100%;height:100%}.geo-frame circle{cursor:pointer}.geo-details{padding:12px;border:1px solid var(--muted);border-radius:8px;display:grid;gap:8px}.geo-details h2,.geo-details h3{margin:0}.geo-details button[aria-pressed=true]{outline:2px solid var(--brand-blue,#18529d)}.geo-list{padding:0;list-style:none;display:grid;gap:8px}.geo-list small{display:block;opacity:.7}.geo-atlas button{min-height:36px}.geo-atlas input[type=search]{flex:1;min-width:180px}.geo-workspace{display:grid;grid-template-columns:minmax(0,2fr) minmax(240px,1fr);gap:12px;align-items:start}.geo-visual{max-height:76dvh;overflow:auto;scroll-margin-top:12px}.geo-results{height:76dvh;overflow:auto;overscroll-behavior:contain;padding:8px;border:1px solid var(--muted);border-radius:8px}.geo-results .geo-list small{max-height:2.8em;overflow:hidden;font-size:12px}.geo-details{max-height:26dvh;overflow:auto;scroll-margin-top:12px}.geo-details details p{max-height:140px;overflow:auto}@media(max-width:640px){.geo-workspace{grid-template-columns:1fr}.geo-frame{position:relative;height:38dvh;min-height:220px}.geo-visual{max-height:68dvh}.geo-results{height:28dvh}.geo-details{max-height:26dvh}} </style>
