package com.bibledesktop.myapp.ui.study

internal data class GeoTexts(val title:String,val search:String,val context:String,val empty:String,val error:String,val retry:String,val reset:String,val fullscreen:String,val back:String,val variants:String,val score:String,val unknown:String,val refs:String,val sources:String,val journey:String,val schematic:String,val uncertain:String,val names:String)
internal fun geoTexts(language:String)=when(language){
 "ru"->GeoTexts("Библейский атлас","Найти место","Использовать исходные OSIS выбранных стихов","Нет мест с опубликованными координатами.","Не удалось загрузить карту.","Повторить","Весь мир","На весь экран","Назад","Варианты расположения","Оценка источника","Оценка не опубликована","Упоминания","Источники и лицензии","Первое путешествие Павла","Линии соединяют места в порядке Деян. 13–14. Это схема, а не восстановленный путь. Расположение зависит от выбранного варианта.","Идентификации исторических мест могут быть спорными. Баллы — оценки OpenBible, не вероятность и не оценка приложения.","Названия и варианты сохранены из источника.")
 "de"->GeoTexts("Bibelatlas","Ort suchen","Original-OSIS der gewählten Verse verwenden","Keine Orte mit veröffentlichten Koordinaten.","Karte konnte nicht geladen werden.","Erneut versuchen","Weltkarte","Vollbild","Zurück","Standortvarianten","Quellenbewertung","Keine Bewertung veröffentlicht","Erwähnungen","Quellen und Lizenzen","Erste Reise des Paulus","Linien verbinden Orte nach Apg. 13–14. Eine Skizze, kein rekonstruierter Reiseweg. Orte hängen von gewählten Varianten ab.","Historische Ortsidentifikationen können umstritten sein. Werte sind OpenBible-Bewertungen, keine Wahrscheinlichkeiten oder App-Bewertungen.","Namen und Varianten stammen unverändert aus der Quelle.")
 "uk"->GeoTexts("Біблійний атлас","Знайти місце","Використовувати вихідні OSIS вибраних віршів","Немає місць з опублікованими координатами.","Не вдалося завантажити карту.","Повторити","Увесь світ","На весь екран","Назад","Варіанти розташування","Оцінка джерела","Оцінку не опубліковано","Згадки","Джерела та ліцензії","Перша подорож Павла","Лінії з’єднують місця в порядку Діян. 13–14. Це схема, а не відновлений шлях. Місця залежать від вибраного варіанта.","Ідентифікації історичних місць можуть бути спірними. Бали — оцінки OpenBible, не ймовірність і не оцінка застосунку.","Назви та варіанти збережено з джерела.")
 else->GeoTexts("Bible atlas","Find a place","Use original OSIS of selected verses","No places with published coordinates.","Could not load the map.","Retry","World map","Fullscreen","Back","Location alternatives","Source score","No published score","Mentions","Sources and licenses","Paul’s first journey","Lines connect places in Acts 13–14 order. A schematic, not a reconstructed travel route. Locations depend on selected alternatives.","Historical identifications may be disputed. Scores are OpenBible assessments, not probabilities or app assessments.","Names and variants are preserved from the source.")
}
internal fun geoNumberingNotice(language:String)=when(language){
 "ru"->"Нумерация атласа: английская протестантская Библия. Соответствие нумерации вашей редакции не подтверждено. Фильтр ниже использует исходные OSIS без пересчёта."
 "de"->"Atlasnummerierung: englische protestantische Bibel. Die Entsprechung zur Nummerierung Ihrer Ausgabe ist nicht bestätigt. Der Filter nutzt die Original-OSIS ohne Umrechnung."
 "uk"->"Нумерація атласу: англійська протестантська Біблія. Відповідність нумерації вашої редакції не підтверджено. Фільтр використовує вихідні OSIS без перерахунку."
 else->"Atlas numbering: English Protestant Bible. Correspondence to your edition’s numbering is unverified. The filter uses original OSIS without conversion."
}
internal fun geoZoomDescription(language:String,increase:Boolean)=when(language){"ru"->if(increase)"Увеличить масштаб"else"Уменьшить масштаб";"de"->if(increase)"Vergrößern"else"Verkleinern";"uk"->if(increase)"Збільшити масштаб"else"Зменшити масштаб";else->if(increase)"Zoom in"else"Zoom out"}
