<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { createPersonalStudyRepository } from '@/offline/personalStudy'
import { emptyPersonalStudy, passageReference, formatPassage, type StudyBookmark } from '@/services/personalStudy'
import { savedVerseLink } from '@/services/readerActions'
import { useI18n } from '@/i18n'
import { personalColorName, personalStudyMessages } from '@/i18n/personalStudy'
const {language}=useI18n(),text=computed(()=>personalStudyMessages[language.value]),repository=createPersonalStudyRepository()
const data=ref(emptyPersonalStudy()),query=ref(''),collection=ref(''),error=ref(''),editing=ref(''),title=ref(''),description=ref(''),draftCollection=ref(''),shown=ref(new Set<string>())
const editingWord=ref(''),wordNote=ref('')
const collections=computed(()=>[...new Set(data.value.bookmarks.map(b=>b.collection).filter(Boolean))].sort())
const entries=computed(()=>data.value.bookmarks.filter(b=>(!collection.value||b.collection===collection.value)&&`${b.title} ${b.description}`.toLocaleLowerCase().includes(query.value.toLocaleLowerCase())).sort((a,b)=>a.collection.localeCompare(b.collection)||a.order-b.order))
onMounted(async()=>{try{data.value=await repository.read()}catch{error.value=text.value.failed}})
async function update(transform:Parameters<typeof repository.update>[0]){try{data.value=await repository.update(transform)}catch{error.value=text.value.failed}}
function edit(b:StudyBookmark){editing.value=b.id;title.value=b.title;description.value=b.description;draftCollection.value=b.collection}
async function save(){await update(d=>({...d,bookmarks:d.bookmarks.map(b=>b.id===editing.value?{...b,title:title.value.trim(),description:description.value.trim(),collection:draftCollection.value.trim(),order:b.collection===draftCollection.value.trim()?b.order:d.bookmarks.filter(x=>x.collection===draftCollection.value.trim()).length}:b)}));editing.value=''}
async function move(b:StudyBookmark,direction:number){const same=data.value.bookmarks.filter(x=>x.collection===b.collection).sort((a,c)=>a.order-c.order),at=same.findIndex(x=>x.id===b.id),other=same[at+direction];if(!other)return;[same[at],same[at+direction]]=[other,b];const orders=new Map(same.map((x,i)=>[x.id,i]));await update(d=>({...d,bookmarks:d.bookmarks.map(x=>orders.has(x.id)?{...x,order:orders.get(x.id)!}:x)}))}
function toggle(id:string){const next=new Set(shown.value);if(next.has(id))next.delete(id);else next.add(id);shown.value=next}
</script>
<template>
<section class="study-library"><h2>{{text.library}}</h2><p v-if="error" role="alert">{{error}}</p><label>{{text.search}}<input v-model="query" type="search" /></label><label>{{text.collection}}<select v-model="collection"><option value="">{{text.all}}</option><option v-for="name in collections" :key="name">{{name}}</option></select></label>
<article v-for="b in entries" :key="b.id" class="study-card" :style="{'border-left':`5px solid ${data.palette[b.color]?.day??'#aaa'}`}"><RouterLink :to="savedVerseLink({...b.passage,chapter:b.passage.start.chapter,verse:b.passage.start.verse})"><strong>{{b.title}}</strong> · {{passageReference(b.passage)}}</RouterLink><small>{{b.passage.translationName}} · {{b.collection}}</small><p>{{b.description}}</p><details><summary>{{text.show}}</summary><p class="passage-text">{{formatPassage(b.passage,{reference:false,translation:false,numbers:true})}}</p></details>
<form v-if="editing===b.id" @submit.prevent="save"><label>{{text.heading}}<input v-model="title" required maxlength="200" /></label><label>{{text.description}}<textarea v-model="description" maxlength="10000" /></label><label>{{text.collection}}<input v-model="draftCollection" maxlength="100" /></label><button>{{text.save}}</button></form>
<div class="row"><button @click="edit(b)">{{text.edit}}</button><button @click="move(b,-1)">{{text.up}}</button><button @click="move(b,1)">{{text.down}}</button><button @click="update(d=>({...d,bookmarks:d.bookmarks.filter(x=>x.id!==b.id)}))">{{text.remove}}</button></div></article>
<p v-if="!entries.length">{{text.empty}}</p><h3>{{text.memory}}</h3><article v-for="card in data.cards" :key="card.id" class="study-card"><RouterLink :to="savedVerseLink({...card.passage,chapter:card.passage.start.chapter,verse:card.passage.start.verse})">{{passageReference(card.passage)}}</RouterLink><small>{{card.passage.translationName}}</small><button @click="toggle(card.id)">{{shown.has(card.id)?text.hide:text.show}}</button><p v-if="shown.has(card.id)" class="passage-text">{{formatPassage(card.passage,{reference:false,translation:false,numbers:false})}}</p><label><input type="checkbox" :checked="card.learned" @change="update(d=>({...d,cards:d.cards.map(x=>x.id===card.id?{...x,learned:!x.learned}:x)}))" />{{card.learned?text.learned:text.learning}}</label><button @click="update(d=>({...d,cards:d.cards.filter(x=>x.id!==card.id)}))">{{text.remove}}</button></article>
<RouterLink to="/notifications">{{text.reminder}} →</RouterLink><h3>{{text.wordNotes}}</h3><article v-for="mark in data.marks.filter(m=>m.note)" :key="mark.id" class="study-card"><strong>{{mark.osis}} · {{mark.code}} · {{mark.quote}}</strong><form v-if="editingWord===mark.id" @submit.prevent="update(d=>({...d,marks:d.marks.map(x=>x.id===mark.id?{...x,note:wordNote.trim()}:x)}));editingWord=''"><label>{{text.note}}<textarea v-model="wordNote" maxlength="10000" /></label><button>{{text.save}}</button></form><template v-else><p>{{mark.note}}</p><button @click="editingWord=mark.id;wordNote=mark.note">{{text.edit}}</button></template><button @click="update(d=>({...d,marks:d.marks.filter(x=>x.id!==mark.id)}))">{{text.remove}}</button></article>
<details><summary>{{text.palette}}</summary><div v-for="(colors,name) in data.palette" :key="name" class="row"><strong>{{personalColorName(name,language)}}</strong><label>{{text.day}}<input type="color" :value="colors.day" @change="update(d=>({...d,palette:{...d.palette,[name]:{...d.palette[name]!,day:($event.target as HTMLInputElement).value}}}))" /></label><label>{{text.night}}<input type="color" :value="colors.night" @change="update(d=>({...d,palette:{...d.palette,[name]:{...d.palette[name]!,night:($event.target as HTMLInputElement).value}}}))" /></label></div></details></section>
</template>
<style scoped>.study-library{display:grid;gap:12px}.study-library label{display:grid;gap:4px}.study-card{padding:12px;background:var(--white);border-radius:8px;display:grid;gap:8px}.row{display:flex;gap:8px;flex-wrap:wrap}.passage-text{white-space:pre-wrap;line-height:1.6}</style>
