package com.bibledesktop.myapp.ui.bible

private val personalEn = mapOf("title" to "Passage and personal study", "start" to "From chapter:verse", "end" to "To chapter:verse", "select" to "Select passage", "invalid" to "The passage is unavailable or incomplete. Check both boundaries.", "reference" to "Include reference", "translation" to "Include translation", "numbers" to "Verse numbers", "copy" to "Copy text", "share" to "Share", "bookmark" to "Save bookmark", "memory" to "Memorization", "saved" to "Saved on this device", "failed" to "Could not save or share. Try again.", "heading" to "Title", "description" to "Description", "collection" to "Collection", "color" to "Color", "word" to "Word marks", "wordHint" to "Select words using the selection handles below. Marks stay in this edition only.", "highlight" to "Highlight", "underline" to "Underline", "note" to "Word note", "erase" to "Erase selected portion", "stale" to "Text changed: older marks are preserved but not attached to new words.", "library" to "Collections and memorization", "search" to "Search title or description", "all" to "All collections", "remove" to "Delete", "edit" to "Edit", "save" to "Save", "up" to "Move up", "down" to "Move down", "show" to "Show text", "hide" to "Hide text", "learned" to "Learned", "learning" to "Learning", "empty" to "No saved passages", "palette" to "Day / night palette", "day" to "Day color", "night" to "Night color", "wordNotes" to "Word notes", "reminder" to "Reminders", "close" to "Close")
private val personalRu = mapOf("title" to "Отрывок и личное изучение", "start" to "От главы:стиха", "end" to "До главы:стиха", "select" to "Выделить отрывок", "invalid" to "Отрывок недоступен или неполон. Проверьте обе границы.", "reference" to "Добавить ссылку", "translation" to "Добавить перевод", "numbers" to "Номера стихов", "copy" to "Скопировать текст", "share" to "Поделиться", "bookmark" to "Сохранить закладку", "memory" to "Заучивание", "saved" to "Сохранено на этом устройстве", "failed" to "Не удалось сохранить или отправить. Повторите.", "heading" to "Заголовок", "description" to "Описание", "collection" to "Подборка", "color" to "Цвет", "word" to "Пометки слов", "wordHint" to "Выделите слова с помощью маркеров выделения ниже. Пометки остаются только в этой редакции.", "highlight" to "Подкрасить", "underline" to "Подчеркнуть", "note" to "Примечание к словам", "erase" to "Ластик для выбранной части", "stale" to "Текст изменился: прежние пометки сохранены, но к новым словам не привязаны.", "library" to "Подборки и заучивание", "search" to "Поиск заголовка или описания", "all" to "Все подборки", "remove" to "Удалить", "edit" to "Изменить", "save" to "Сохранить", "up" to "Выше", "down" to "Ниже", "show" to "Показать текст", "hide" to "Скрыть текст", "learned" to "Выучено", "learning" to "Изучается", "empty" to "Нет сохранённых отрывков", "palette" to "Дневная / ночная палитра", "day" to "Дневной цвет", "night" to "Ночной цвет", "wordNotes" to "Примечания к словам", "reminder" to "Напоминания", "close" to "Закрыть")
private val personalDe = mapOf("title" to "Abschnitt und persönliches Studium", "start" to "Von Kapitel:Vers", "end" to "Bis Kapitel:Vers", "select" to "Abschnitt auswählen", "invalid" to "Abschnitt fehlt oder ist unvollständig. Grenzen prüfen.", "reference" to "Bibelstelle hinzufügen", "translation" to "Übersetzung hinzufügen", "numbers" to "Versnummern", "copy" to "Text kopieren", "share" to "Teilen", "bookmark" to "Lesezeichen speichern", "memory" to "Auswendiglernen", "saved" to "Auf diesem Gerät gespeichert", "failed" to "Speichern oder Teilen fehlgeschlagen.", "heading" to "Titel", "description" to "Beschreibung", "collection" to "Sammlung", "color" to "Farbe", "word" to "Wortmarkierungen", "wordHint" to "Wörter mit den Auswahlgriffen auswählen. Markierungen bleiben nur in dieser Ausgabe.", "highlight" to "Markieren", "underline" to "Unterstreichen", "note" to "Wortnotiz", "erase" to "Ausgewählten Teil löschen", "stale" to "Text geändert: alte Markierungen bleiben erhalten, werden aber nicht neu zugeordnet.", "library" to "Sammlungen und Auswendiglernen", "search" to "Titel oder Beschreibung suchen", "all" to "Alle Sammlungen", "remove" to "Löschen", "edit" to "Bearbeiten", "save" to "Speichern", "up" to "Nach oben", "down" to "Nach unten", "show" to "Text zeigen", "hide" to "Text verbergen", "learned" to "Gelernt", "learning" to "In Arbeit", "empty" to "Keine gespeicherten Abschnitte", "palette" to "Tag-/Nachtpalette", "day" to "Tagfarbe", "night" to "Nachtfarbe", "wordNotes" to "Wortnotizen", "reminder" to "Erinnerungen", "close" to "Schließen")
private val personalUk = personalRu + mapOf("title" to "Уривок та особисте вивчення", "start" to "Від глави:вірша", "end" to "До глави:вірша", "select" to "Виділити уривок", "invalid" to "Уривок недоступний або неповний. Перевірте обидві межі.", "reference" to "Додати посилання", "translation" to "Додати переклад", "numbers" to "Номери віршів", "copy" to "Скопіювати текст", "share" to "Поділитися", "bookmark" to "Зберегти закладку", "memory" to "Заучування", "saved" to "Збережено на цьому пристрої", "failed" to "Не вдалося зберегти чи надіслати.", "heading" to "Заголовок", "description" to "Опис", "collection" to "Добірка", "color" to "Колір", "word" to "Позначки слів", "wordHint" to "Виділіть слова маркерами виділення нижче. Позначки залишаються лише в цій редакції.", "highlight" to "Підфарбувати", "underline" to "Підкреслити", "note" to "Примітка до слів", "erase" to "Гумка для вибраної частини", "stale" to "Текст змінився: старі позначки збережені, але до нових слів не прив’язані.", "library" to "Добірки та заучування", "search" to "Пошук заголовка чи опису", "all" to "Усі добірки", "remove" to "Видалити", "edit" to "Змінити", "save" to "Зберегти", "up" to "Вище", "down" to "Нижче", "show" to "Показати текст", "hide" to "Приховати текст", "learned" to "Вивчено", "learning" to "Вивчається", "empty" to "Немає збережених уривків", "palette" to "Денна / нічна палітра", "day" to "Денний колір", "night" to "Нічний колір", "wordNotes" to "Примітки до слів", "reminder" to "Нагадування", "close" to "Закрити")
internal fun personalStudyText(language: String, key: String): String = (when (language) { "ru" -> personalRu; "de" -> personalDe; "uk" -> personalUk; else -> personalEn })[key] ?: personalEn.getValue(key)

internal fun personalColorName(language:String,name:String):String {
    val labels=when(language){"ru"->listOf("Жёлтый","Зелёный","Синий","Розовый");"de"->listOf("Gelb","Grün","Blau","Rosa");"uk"->listOf("Жовтий","Зелений","Синій","Рожевий");else->listOf("Yellow","Green","Blue","Pink")}
    val index=listOf("yellow","green","blue","pink").indexOf(name)
    return if(index>=0)labels[index]else name
}
