package com.bibledesktop.myapp.ui.bible

internal fun readerControlText(language: String, key: String): String {
    if(key=="day")return when(language){"ru"->"Дневной режим";"de"->"Tagmodus";"uk"->"Денний режим";else->"Day mode"}
    val names = listOf("settings","history","back","forward","close","favorites","all","favorite","unfavorite","fontSize","lineHeight","chapterLabels","verseNumbers","separateVerses","headings","crossReferences","commentaryLinks","footnotes","strongNumbers","paragraphs","addedWords","clean","night","tapPaging","swipeChapters","swipeBooks","volumePaging","available","visual","digital","go","beginning","invalid")
    val strings = when(language) {
        "ru" -> listOf("Отображение и управление","История переходов","Назад","Вперёд","Закрыть","Избранные переводы","Все переводы","В избранное","Убрать из избранного","Размер текста","Межстрочный интервал","Обозначения глав","Номера стихов","Стихи с новой строки","Подзаголовки","Перекрёстные ссылки","Ссылки на толкования","Сноски","Номера Стронга","Абзацы источника","Оформление добавленных слов","Чистый текст","Ночной режим","Касание краёв: экран назад / вперёд","Один палец: главы","Два пальца: книги","Кнопки громкости: прокрутка","Элементы отображаются только при наличии в источнике. Если исходная разметка не сохранена, подзаголовки, сноски и оформление не восстанавливаются.","Сетка","Глава:стих","Перейти","В начало","Такого места нет в выбранном тексте.")
        "de" -> listOf("Darstellung und Bedienung","Verlauf","Zurück","Vorwärts","Schließen","Lieblingsübersetzungen","Alle Übersetzungen","Als Favorit","Favorit entfernen","Schriftgröße","Zeilenabstand","Kapitelbezeichnungen","Versnummern","Verse in neuen Zeilen","Zwischenüberschriften","Querverweise","Kommentarverweise","Fußnoten","Strong-Nummern","Absätze der Quelle","Hinzugefügte Wörter","Reiner Text","Nachtmodus","Rand antippen: Seite zurück / weiter","Ein Finger: Kapitel","Zwei Finger: Bücher","Lautstärketasten: scrollen","Elemente erscheinen nur, wenn sie in der Quelle enthalten sind. Nicht gespeicherte Quellenauszeichnungen, Überschriften und Fußnoten werden nicht rekonstruiert.","Raster","Kapitel:Vers","Öffnen","Zum Anfang","Diese Stelle fehlt im ausgewählten Text.")
        "uk" -> listOf("Відображення та керування","Історія переходів","Назад","Вперед","Закрити","Обрані переклади","Усі переклади","До обраного","Вилучити з обраного","Розмір тексту","Міжрядковий інтервал","Позначення розділів","Номери віршів","Вірші з нового рядка","Підзаголовки","Перехресні посилання","Посилання на тлумачення","Виноски","Номери Стронга","Абзаци джерела","Оформлення доданих слів","Чистий текст","Нічний режим","Дотик країв: екран назад / вперед","Один палець: розділи","Два пальці: книги","Кнопки гучності: прокручування","Елементи показуються лише за наявності у джерелі. Якщо вихідну розмітку не збережено, підзаголовки, виноски й оформлення не відновлюються.","Сітка","Розділ:вірш","Перейти","На початок","Цього місця немає у вибраному тексті.")
        else -> listOf("Display and controls","Navigation history","Back","Forward","Close","Favorite translations","All translations","Add favorite","Remove favorite","Text size","Line spacing","Chapter labels","Verse numbers","Verses on separate lines","Headings","Cross references","Commentary links","Footnotes","Strong numbers","Source paragraphs","Style added words","Clean text","Night mode","Tap edges: previous / next screen","One finger: chapters","Two fingers: books","Volume buttons: scroll","Elements appear only when present in the source. Missing source markup, headings and footnotes are not reconstructed.","Grid","Chapter:verse","Go","To beginning","This passage does not exist in the selected text.")
    }
    return strings.getOrElse(names.indexOf(key)) { key }
}
